
sudo: true

language: cpp
cache:
  apt: true

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'g++-5']
      env:
        - COMPILERCC=gcc-5
        - COMPILERCXX=g++-5

    - os: linux
      dist: trusty
      compiler: clang
      addons:
        apt:
          sources: ['llvm-toolchain-trusty-4.0']
          packages: ['clang-4.0']
      env:
        - COMPILERCC=clang-4.0
        - COMPILERCXX=clang++-4.0


    - os: osx
      compiler: gcc
      env:
        - COMPILERCC=gcc
        - COMPILERCXX=g++

    - os: osx
      compiler: clang
      env:
        - COMPILERCC=clang
        - COMPILERCXX=clang++


script:
  - mkdir build
  - cd build
  - export CC=$COMPILERCC; export CXX=$COMPILERCXX
  - cmake .. -DEDIMPL=ref10 -DHASH=sha3_brainhub -DRANDOM=dev_urandom
  - make
  - ctest